application: tile5js
version: 5
runtime: python
api_version: 1

handlers:
- url: /tile/.*
  script: tile.py
  
- url: /(.*\.(html|js|css|gif|png|jpg|xml|json|txt|ico|swf|mp3|ogg))
  static_files: \1
  upload: (.*\.(html|js|css|gif|png|jpg|xml|json|txt|ico|swf|mp3|ogg))

- url: /tag/(.*/?)
  static_files: category/\1index.html
  upload: category/(.*/?)index.html

- url: /
  static_files: index.html
  upload: index.html  

- url: /(.*/)
  static_files: \1index.html
  upload: (.*/)index.html  

- url: /(.*/?)
  static_files: \1/index.html
  upload: (.*/?)index.html