application: tile5js
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /media
  static_dir: media
  
- url: /favicon.ico
  static_dir: media/img

- url: /.*
  script: main.py
